// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package account

import (
	"gf-playground-1/api/account"
	accountLogic "gf-playground-1/internal/logic/account"
)

type ControllerV1 struct {
	account *accountLogic.Account
}

func NewV1() account.IAccountV1 {
	return &ControllerV1{
		account: accountLogic.New(),
	}
}
