// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package users

import (
	"gf-playground-1/api/users"
	usersLogic "gf-playground-1/internal/logic/users"
)

type ControllerV1 struct {
	users *usersLogic.Users
}

func NewV1() users.IUsersV1 {
	return &ControllerV1{
		users: usersLogic.New(),
	}

}
